Hw04 auth
TanyaKalkuta/nodejs-homework-rest-api pull request #3
Opened 2021-09-10 14:54 UTC by TanyaKalkuta

Перевірьте, будь ласка!

2021-09-11 11:06 UTC, Danil44 requested changes

2021-09-11 11:06 UTC, Danil44 commented on controllers/auth/current.js
> +/* 2й способ:
В пул реквесті не має бути закоментованого коду

2021-09-11 22:15 UTC, TanyaKalkuta commented on controllers/auth/current.js
> +/* 2й способ:
десь коміт загубився був. запушила

2021-09-12 12:29 UTC, Danil44 approved these changes

2021-09-12 12:29 UTC, Danil44 commented on middlewares/authenticate.js
> +    if (bearer !== 'Bearer') {
Чому перевірка саме на стрічку "Bearer"?

2021-09-12 12:29 UTC, merged